//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paygl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paygl.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string _btnAccept {
            get {
                return ResourceManager.GetString("_btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string _btnAdd {
            get {
                return ResourceManager.GetString("_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string _btnAddGroup {
            get {
                return ResourceManager.GetString("_btnAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add manually.
        /// </summary>
        public static string _btnAddManualy {
            get {
                return ResourceManager.GetString("_btnAddManualy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string _btnAnalyse {
            get {
                return ResourceManager.GetString("_btnAnalyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string _btnAnalysis {
            get {
                return ResourceManager.GetString("_btnAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Manager.
        /// </summary>
        public static string _btnAnalysisManager {
            get {
                return ResourceManager.GetString("_btnAnalysisManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string _btnBack {
            get {
                return ResourceManager.GetString("_btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string _btnCancel {
            get {
                return ResourceManager.GetString("_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean.
        /// </summary>
        public static string _btnClear {
            get {
                return ResourceManager.GetString("_btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string _btnConfirm {
            get {
                return ResourceManager.GetString("_btnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide into 2 transactions.
        /// </summary>
        public static string _btnDivideIntoTwo {
            get {
                return ResourceManager.GetString("_btnDivideIntoTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string _btnFilters {
            get {
                return ResourceManager.GetString("_btnFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string _btnIgnore {
            get {
                return ResourceManager.GetString("_btnIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string _btnImport {
            get {
                return ResourceManager.GetString("_btnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string _btnNext {
            get {
                return ResourceManager.GetString("_btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string _btnSave {
            get {
                return ResourceManager.GetString("_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string _btnSaveAs {
            get {
                return ResourceManager.GetString("_btnSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string _btnSearching {
            get {
                return ResourceManager.GetString("_btnSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string _btnShow {
            get {
                return ResourceManager.GetString("_btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string _btnTransactions {
            get {
                return ResourceManager.GetString("_btnTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string _lblAmount {
            get {
                return ResourceManager.GetString("_lblAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated with:.
        /// </summary>
        public static string _lblAssociatedWith {
            get {
                return ResourceManager.GetString("_lblAssociatedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string _lblDate {
            get {
                return ResourceManager.GetString("_lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string _lblDateFormat {
            get {
                return ResourceManager.GetString("_lblDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string _lblDescription {
            get {
                return ResourceManager.GetString("_lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency:.
        /// </summary>
        public static string _lblFrequence {
            get {
                return ResourceManager.GetString("_lblFrequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string _lblFrom {
            get {
                return ResourceManager.GetString("_lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance:.
        /// </summary>
        public static string _lblImportance {
            get {
                return ResourceManager.GetString("_lblImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string _lblName {
            get {
                return ResourceManager.GetString("_lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New description:.
        /// </summary>
        public static string _lblNewDescription {
            get {
                return ResourceManager.GetString("_lblNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulatively:.
        /// </summary>
        public static string _lblSum {
            get {
                return ResourceManager.GetString("_lblSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        public static string _lblTags {
            get {
                return ResourceManager.GetString("_lblTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string _lblTo {
            get {
                return ResourceManager.GetString("_lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction type:.
        /// </summary>
        public static string _lblTransactionType {
            get {
                return ResourceManager.GetString("_lblTransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer type:.
        /// </summary>
        public static string _lblTransferType {
            get {
                return ResourceManager.GetString("_lblTransferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add view.
        /// </summary>
        public static string addFiltersGroupRN {
            get {
                return ResourceManager.GetString("addFiltersGroupRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string addGroupRN {
            get {
                return ResourceManager.GetString("addGroupRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add manually.
        /// </summary>
        public static string addManualyRN {
            get {
                return ResourceManager.GetString("addManualyRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string analyseRN {
            get {
                return ResourceManager.GetString("analyseRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string analysisManagerRN {
            get {
                return ResourceManager.GetString("analysisManagerRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string dateFormat {
            get {
                return ResourceManager.GetString("dateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit:.
        /// </summary>
        public static string editFilterRN {
            get {
                return ResourceManager.GetString("editFilterRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit:.
        /// </summary>
        public static string editFiltersGroupRN {
            get {
                return ResourceManager.GetString("editFiltersGroupRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit:.
        /// </summary>
        public static string editGroupRN {
            get {
                return ResourceManager.GetString("editGroupRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit:.
        /// </summary>
        public static string editManualyRN {
            get {
                return ResourceManager.GetString("editManualyRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string filtersRN {
            get {
                return ResourceManager.GetString("filtersRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string importRN {
            get {
                return ResourceManager.GetString("importRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful modification.
        /// </summary>
        public static string messageBoxModificationSuccess {
            get {
                return ResourceManager.GetString("messageBoxModificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement.
        /// </summary>
        public static string messageBoxStatement {
            get {
                return ResourceManager.GetString("messageBoxStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong query.
        /// </summary>
        public static string messageBoxWrongQuery {
            get {
                return ResourceManager.GetString("messageBoxWrongQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string searchingRN {
            get {
                return ResourceManager.GetString("searchingRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expense.
        /// </summary>
        public static string transactionTypeExpense {
            get {
                return ResourceManager.GetString("transactionTypeExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to income.
        /// </summary>
        public static string transactionTypeIncome {
            get {
                return ResourceManager.GetString("transactionTypeIncome", resourceCulture);
            }
        }
    }
}
